# Generated by Django 5.0.6 on 2024-05-20 15:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='La dirección debe terminar en un número.', regex='.*\\d$')])),
                ('ciudad', models.CharField(max_length=100)),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
                ('fecha_fundacion', models.DateField()),
                ('normas', models.FileField(blank=True, null=True, upload_to='normas/')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('sinopsis', models.TextField()),
                ('anio_publicacion', models.DateField()),
                ('editorial', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='El ISBN debe tener el formato 0-7645-2641-3.', regex='^\\d{1,5}-\\d{1,7}-\\d{1,7}-\\d{1,7}-\\d{1,7}$')])),
                ('num_ejemplares', models.IntegerField()),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.biblioteca')),
            ],
        ),
    ]
